spring:
  profiles:
    active: db, core
  messages:
    encoding: UTF-8

logging:
  level:
    root:  info
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall:  ERROR
    org.tlh.dw: info

simulate:
  baseUrl: http://log-center