server:
  port: 8085
  servlet:
    context-path: /dw

spring:
  datasource:
    url:  jdbc:mysql://storage:3306/litemall_report?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username:  litemall
    password:  litemall123456
report:
  admin:
    host: http://localhost:8083
    auth-info: /admin/auth/info