server:
  port: 8085
  servlet:
    context-path: /dw

spring:
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          url: jdbc:mysql://storage:3306/litemall_report?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: litemall
          password: litemall123456
        clickhouse:
          url: jdbc:clickhouse://hadoop-master:8123/litemall
          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
          username: default
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/{vendor}
  redis:
    host: storage
    port: 6379
    database: 0
report:
  admin:
    host: http://localhost:8083
    auth-info: /admin/auth/info