server:
  port: 8086
  servlet:
    context-path: /profile

spring:
  datasource:
    url:  jdbc:mysql://storage:3306/user_profile?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username:  litemall
    password:  litemall123456
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/{vendor}

profile:
  admin:
    host: http://localhost:8083
    auth-info: /admin/auth/info