server:
  port: 8086
  servlet:
    context-path: /tag

spring:
  datasource:
    url:  jdbc:mysql://storage:3306/user_profile?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username:  litemall
    password:  litemall123456
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/{vendor}
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  data:
    solr:
      host: http://cdh-master:8983/solr

profile:
  admin:
    host: http://localhost:8083
    auth-info: /admin/auth/info
  hdfs:
    url: hdfs://cdh-master:8020
    model-path: /app/litemall/model
    oozie-path: /app/litemall/oozie
    user: oozie
  oozie:
    url: http://cdh-master:11000/oozie
    user: oozie
    resource-manager: cdh-master:8032
    name-node: hdfs://cdh-master:8020
    spark-opts: --executor-memory 1G --num-executors 1

auth:
  admin:
    enable: true
    host: http://localhost:8083
    auth-info: /admin/auth/info